### ISSUE TITLE
Tests don't pass on Solidus 2.6

### ISSUE THREAD

**Issue by jeffreyguenther** [solidusio-contrib/solidus_tax_cloud#14]
I'm opening this issue to provide a place to chat about what needs to be done to get the tests passing for 2.6. I intend to follow up this issue with a PR addressing these issues.

Here's the list of failing tests:
``` bash
rspec ./spec/features/checkout_spec.rb:41 # Checkout should display tax lookup error if invalid address
rspec ./spec/features/checkout_spec.rb:68 # Checkout should calculate and display tax on payment step and allow full checkout
rspec ./spec/features/checkout_spec.rb:82 # Checkout should not break when removing all items from cart after a tax calculation has been created
rspec ./spec/features/checkout_spec.rb:118 # Checkout TaxCloud Test Case 1a: Verify Address with error
rspec ./spec/features/checkout_spec.rb:142 # Checkout TaxCloud Test Case 1b: Verify Address without error
rspec ./spec/features/checkout_spec.rb:163 # Checkout TaxCloud Test Case 2a: If all items in cart are tax exempt, shipping is not taxed (in some states)
rspec ./spec/features/checkout_spec.rb:189 # Checkout TaxCloud Test Case 2b: With both taxable and tax exempt items, shipping is taxable
rspec ./spec/features/checkout_spec.rb:213 # Checkout TaxCloud Test Case 3: Item taxable, shipping not taxable
rspec ./spec/features/checkout_spec.rb:245 # Checkout TaxCloud Test Case 6: Item and shipping taxable
```

I think a number are due to address verification failing.

**Comment by jeffreyguenther** [comment]
@brchristian At what stage in the checkout process is it expected that an invalid address will redirect back to the address step? Is it supposed to happen after clicking "Place Order"?

**Comment by jeffreyguenther** [comment]
I have not been able to figure out why yet, but the best I can tell is is that `TaxCloud::Errors::ApiError` is not being raised and then caught on https://github.com/solidusio-contrib/solidus_tax_cloud/blob/d4b5795932819e94a9194cfa52f69c47d75c4aee/app/controllers/spree/frontend/checkout_controller_decorator.rb#L7

**Comment by jeffreyguenther** [comment]
The causes of the other failures might be different. I haven't been able to work my way through them all yet.

**Comment by brchristian** [comment]
Hi @jeffreyguenther my best guess is that the issue you were having was caused not by Solidus 2.6 but by Rails 5.2 – which radically changed the way that lower-level caching is handled. The solids_tax_cloud extension now supports both the new and old syntax, and our Travis builds are passing in Solidus 2.5, 2.6, 2.7 and master. As a result I am closing this issue, but feel free to speak up if you encounter any further issues. Cheers!
