### ISSUE TITLE
solids_tax_cloud does not work for Rails version 5.2.0 and above

### ISSUE THREAD

**Issue by pathakh** [solidusio-contrib/solidus_tax_cloud#18]
In spree_tax_cloud.gemspec, the change that restrics the rails version has a comment:

https://github.com/solidusio-contrib/solidus_tax_cloud/commit/82bcec58603f52f2e81321e9b5b3b06a05b25272

TODO: Relax this for full Solidus 2.6 support

There is nothing else changed in the commit.  Is there any reason why this dependency needs to be there?

**Comment by brchristian** [comment]
@pathakh Yes, it is there because Rails 5.2 substantially changed the way that Rails performs caching. Until/unless this extension is updated for the Rails 5.2 syntax, it will not work with Rails 5.2. If you would like to make solidus_tax_cloud compatible with Rails 5.2, I would welcome the PR. :)

**Comment by brchristian** [comment]
@pathakh solids_tax_cloud now supports Rails version 5.2, so I am closing this issue. Cheers!

**Comment by pathakh** [comment]
@brchristian thanks.
