### ISSUE TITLE
Configuration is wiped every time I restart server

### ISSUE THREAD

**Issue by funwhilelost** [solidusio-contrib/solidus_tax_cloud#4]
Every time the server is restarted the values in my Settings > Store > TaxCloud Settings are wiped out.

**Comment by brchristian** [comment]
Hmm, I’m not able to reproduce in my app which is on the latest `master`. Are you able to reproduce this in a new Solidus app?

**Comment by rlasch** [comment]
I am seeing this as well, but it's not clear when/why this is happening.  I think I'm going to hunt this down.

**Comment by hf2186** [comment]
Yeah this is happening for me too. Created a new solidus app v2.2

**Comment by hf2186** [comment]
I have a fix for this issue.

**Comment by brchristian** [comment]
@hf2186 PR is welcome! 👍

**Comment by hf2186** [comment]
@brchristian I am new to TravisCI. The PR is failing. Any insight on that would be appreciated.

**Comment by brchristian** [comment]
@funwhilelost The fix from @hf2186 was right on the money. This is now merged to `v2.2`, `v2.3`, and `master`.

**Comment by hf2186** [comment]
Can you update the readme for some reason the formatting become messed up

**Comment by brchristian** [comment]
@hf2186 It looks okay to me - which part is messed up?

**Comment by hf2186** [comment]
Looks right now. It was the 

TaxCloud.configure do |config|
  config.api_login_id = 'YOUR_TAX_CLOUD_API_ID'
  config.api_key = 'YOUR_TAX_CLOUD_API_KEY'
end

**Comment by brchristian** [comment]
What about it is messed up? Sorry for being dense...

**Comment by hf2186** [comment]
It has been fixed with a later commit you just made. Thanks!
