### ISSUE TITLE
DEPRECATION WARNING: SolidusSupport::EngineExtensions::Decorators is deprecated!

### ISSUE THREAD

**Issue by collinsbrian** [solidusio-contrib/solidus_tax_cloud#42]
I have installed the solidus_tax_cloud gem using:

gem 'solidus_tax_cloud', github: 'solidusio-contrib/solidus_tax_cloud'

When i start the rails server i get the below warning:

DEPRECATION WARNING: SolidusSupport::EngineExtensions::Decorators is deprecated! Use SolidusSupport::EngineExtensions instead. (called from <class:Engine> at /Users/briancollins/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/solidus_tax_cloud-e4632b03df4f/lib/solidus_tax_cloud/engine.rb:7)

Does the engine.rb file need modification? 

Rails and Ruby versions below:

[ecommnew (master)]$ rails --version
Rails 6.0.3.1
[ecommnew (master)]$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

thanks

**Comment by kennyadsl** [comment]
Hey @collinsbrian, this is now fixed, thanks for reporting!

**Comment by aldesantis** [comment]
@collinsbrian also, the gem is now on RubyGems :)

**Comment by collinsbrian** [comment]
Thank you all for the quick response and resolution. Well done
